language: rust
sudo: required

cache: cargo

os:
  - linux
  - osx

rust:
  - stable
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libx11-xcb-dev; fi

script:
  - cargo test --no-default-features
